### ISSUE TITLE
Issue with Carrierwave

### ISSUE THREAD

**Issue by tandrieu** [barsoom/traco#23] opened 2014-04-03 06:24 UTC
Hi,

Considering an app with rails 4.0.4, using Traco 3.1 and Carrierwave 0.10.0.
When translating a Carrierwave's attribute, Traco's attribute always returns nil.
That doesn't happen on rails 3.2.17 with same traco and carrierwave's versions.

I did a workaround in my models, for exemple :

```ruby
def logo
    send("logo_#{I18n.locale}")
end
```

Let me know if i can help

Thanks

Thomas

**Comment by henrik** [comment] 2015-01-14 15:26
Closing this since it's not a bug.

**Closed** 2015-01-14 15:26 UTC
